repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Wersja Ruffa
    rev: v0.4.4
    hooks:
      # Linter
      - id: ruff
        args: [ --fix ]
      # Formatter (odpowiednik Blacka)
      - id: ruff-format
